### ISSUE TITLE
`rusty_secrets::sss::generate_shares` returns `String`s?

### ISSUE THREAD

**Issue by burdges** [SpinResearch/RustySecrets#20]
Appears `rusty_secrets::sss::generate_shares` returns `Result<Vec<String>>`, which sounds odd for ciphertext.  In fact, [collections::string::String](https://doc.rust-lang.org/nightly/collections/string/struct.String.html#utf-8) says _"Strings are always valid UTF-8. This has a few implications, the first of which is that if you need a non-UTF-8 string, consider OsString. It is similar, but without the UTF-8 constraint."_  I suppose your encoding via protobuf makes all that fine though and you mean to send this over text channels anyways?

**Comment by FredericJacobs** [comment]
Hey @burdges!
Thanks for looking into RustySecrets.

The reason it was done this way is because in the context of an application that relies on RustySecrets we wanted to return shares in the format described in the [`README`](https://github.com/SpinResearch/RustySecrets#structure-of-the-shares).

I guess you're right that in the `sss` module we could return data and leave it to library consumers to choose how to deal with that.

**Comment by burdges** [comment]
Cool.  I'll close this since it sounds like everything makes sense.
